const HOME_PAGE = 'HOME_PAGE'
const SEARCH_PAGE = 'SEARCH_PAGE'
const BENEFIT_PAGE = 'BENEFIT_PAGE'

const BENEFITS = 'BENEFITS'
const BENEFIT_EI = 'BENEFIT_EI'
const TOP_TASKS = 'TOP_TASKS'
const DICTIONARY = 'DICTIONARY'

module.exports = {
  HOME_PAGE,
  SEARCH_PAGE,
  BENEFITS,
  BENEFIT_EI,
  TOP_TASKS,
  DICTIONARY,
}
