export const TypeCodes = {
  NotActive: 'NotActive',
  DurationReached: 'DurationReached',
  CPPRetirement: 'CPPRetirement',
  CPPSurvivor: 'CPPSurvivor',
  CPPChild: 'CPPChild',
  CPPAllowance: 'CPPAllowance',
  CPPSharing: 'CPPSharing',
  CPPCreditSplit: 'CPPCreditSplit',
  CPPChildRearing: 'CPPChildRearing',
  CPPDeath: 'CPPDeath',
  CPPDisability: 'CPPDisability',
  OASRetirement: 'OASRetirement',
  GISRetirement: 'GISRetirement',
  GISAllowance: 'GISAllowance',
  GISAllowanceSurvivor: 'GISAllowanceSurvivor',
  EISickness: 'EISickness',
  SEBRegular: 'SEBRegular',
}
