export const SummaryTypes = {
  LastNetPayment: 'LastNetPayment',
  NextReport: 'NextReport',
  LatestStatus: 'LatestStatus',
  LatestStatusMessage: 'LatestStatusMessage',
  NextPayment: 'NextPayment',
  RequestedBenefit: 'RequestedBenefit',
  EstimatedDecisionDate: 'EstimatedDecisionDate',
  BenefitAffected: 'BenefitAffected',
  PresentStatus: 'PresentStatus',
  LastPaymentDate: 'LastPaymentDate',
  NextPaymentDate: 'NextPaymentDate',
  LastPayment: 'LastPayment',
  ActiveBenefit: 'ActiveBenefit',
}
