import { ProgramCodes } from '../constants/ProgramCodes'
import { TypeCodes } from '../constants/ProgramTypeCodes'
import { StatusCodes } from '../constants/StatusCodes'
import { SummaryTypes } from '../constants/SummaryTypes'
import {
  CreateGenericBenefitJSONForUserDisplay,
  CreateGenericBenefitSummaryForDisplay,
} from './BenefitsMapping'

export default function GenerateCPPMockData() {
  return [
    CreateGenericBenefitJSONForUserDisplay(
      ProgramCodes.CPP,
      StatusCodes.inactive,
      TypeCodes.CPPRetirement
    ),
    CreateGenericBenefitJSONForUserDisplay(
      ProgramCodes.CPP,
      StatusCodes.applicationReceived,
      TypeCodes.CPPRetirement,
      [
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.RequestedBenefit,
          TypeCodes.CPPRetirement
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.LatestStatus,
          '04-04-2022'
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.EstimatedDecisionDate,
          '06-05-2022'
        ),
      ]
    ),
    CreateGenericBenefitJSONForUserDisplay(
      ProgramCodes.CPP,
      StatusCodes.decisionSent,
      TypeCodes.CPPRetirement,
      [
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.RequestedBenefit,
          TypeCodes.CPPRetirement
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.LatestStatus,
          '04-04-2022'
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.EstimatedDecisionDate,
          '06-05-2022'
        ),
      ]
    ),
    CreateGenericBenefitJSONForUserDisplay(
      ProgramCodes.CPP,
      StatusCodes.paymentHold,
      TypeCodes.CPPRetirement,
      [
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.BenefitAffected,
          TypeCodes.CPPRetirement
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.LatestStatus,
          '04-04-2022'
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.PresentStatus,
          'Suspended'
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.LastPaymentDate,
          '11-10-2021'
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.LastPayment,
          1362.68
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.NextPaymentDate,
          'On hold'
        ),
      ]
    ),
    CreateGenericBenefitJSONForUserDisplay(
      ProgramCodes.CPP,
      StatusCodes.inPayment,
      TypeCodes.CPPRetirement,
      [
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.ActiveBenefit,
          TypeCodes.CPPRetirement
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.LastPaymentDate,
          '11-10-2021'
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.LastPayment,
          1362.68
        ),
        CreateGenericBenefitSummaryForDisplay(
          SummaryTypes.NextPayment,
          '11-11-2021'
        ),
      ]
    ),
  ]
}
